admin:
    path:     /admin
    defaults: { _controller: "Jd2hBundle:Back:admin" }

login:
    path:     /login
    defaults: { _controller: "Jd2hBundle:Back:login"}

logout:
    path:     /logout

back_user:
    path: /user
    defaults: { _controller: "Jd2hBundle:Back:user" }
    methods: GET