back_admin:
    path:     /admin
    defaults: { _controller: "Jd2hBundle:Back:admin" }

back_login:
    path:     /login
    defaults: { _controller: "Jd2hBundle:Back:login"}

back_user:
    path: /user
    defaults: { _controller: "Jd2hBundle:Back:user" }
    methods: GET

back_logout:
    path:     /logout

