front_homepage:
    path: /
    defaults: { _controller: "Jd2hBundle:Front:homepage"}
    methods: GET

front_quisommesnous:
    path: /quisommesnous
    defaults: { _controller: "Jd2hBundle:Front:quisommesnous"}
    methods: GET

front_jedonne:
    path: /jedonne
    defaults: { _controller: "Jd2hBundle:Front:jedonne"}
    methods: GET

front_jepropose:
    path: /jepropose
    defaults: { _controller: "Jd2hBundle:Front:jepropose"}
    methods: GET

front_404:
    path: /*
    defaults: { _controller: "Jd2hBundle:Front:error"}
    methods: GET