front_homepage:
    path: /
    defaults: { _controller: "Jd2hBundle:Front:homepage"}
    methods: GET

front_quisommesnous:
    path: /quisommesnous
    defaults: { _controller: "Jd2hBundle:Front:quisommesnous"}
    methods: GET

front_jedonne:
    path: /jedonne
    defaults: { _controller: "Jd2hBundle:Front:jedonne"}
    methods: [GET, POST]

front_jepropose:
    path: /jepropose
    defaults: { _controller: "Jd2hBundle:Front:jepropose"}
    methods: [GET, POST]

front_inscriptok:
    path: /inscriptionvalide
    defaults: { _controller: "Jd2hBundle:Front:inscriptionok"}
    methods: GET


testRedirection:
    path: /redirection
    defaults: { _controller: "Jd2hBundle:Default:redirection"}
    methods: GET

testMail:
    path: /sendMail
    defaults: { _controller: "Jd2hBundle:Default:sendMail"}
    methods: POST