<?php

namespace Jd2hBundle\Repository;

/**
 * EntrepreneurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntrepreneurRepository extends \Doctrine\ORM\EntityRepository
{
}
