<?php

namespace Jd2hBundle\Repository;

/**
 * Jd2hRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Jd2hRepository extends \Doctrine\ORM\EntityRepository
{
}
